### ISSUE TITLE
Makefile compatibility with linux

### ISSUE THREAD

**Issue by Blizire** [Blizire/bbmp#10]
Changed the makefiles up to make it cleaner and correct some flags. However it was not tested or written for linux.

**Comment by NealsSec** [comment]
Much broken am upset.

**Comment by NealsSec** [comment]
I have added pull request #11 which should address the incompatibilities. 

They are not pretty but... they work.

**Comment by NealsSec** [comment]
I closed #11 and opened #12 to fix a double free in the main lib and to fix a typo in the main lib makefile.

**Comment by Blizire** [comment]
alright dope stuff ill check out the double free. I've been obsessing over
EVE lately. Check this link

https://www.youtube.com/watch?v=sPFII3ozSHI

I think I want to occupy a lot of my time playing this all of a sudden lol

**Comment by NealsSec** [comment]
I didn't realize they went full FTP. I tried to get into it like a year ago but I never really got far. We've been playing a lot of OW lately tbh.

**Comment by Blizire** [comment]
Well overwatch is the shit nigga, speciallly when you drink malt liqua

**Comment by NealsSec** [comment]
Did you ever start playing EVE? I uploaded a first draft of my Router teardown @https://nealssec.github.io/writeups/RE/hardware/netis/netis.html

**Comment by Blizire** [comment]
Yes. I've been HOOKED. Got invited to a corp for asking v specific
questions on complicated ship fittings I read about at work and got
invited. Then they sent me a discord link to listen in on comms. So I
joined and muted and the corp is being ran like a relaxed version of being
the army IRL lmao. Our Commander was telling people to sign contracts
within our corp for the new players to start mining and have the vets do
the reprocessing since they a higher skill/efficiency rating in industry.
Then a whole bunch of us have to train our skills up to pilot a certain
ship were going to be using in 3 weeks ( you should join or at least train
a character up for this ). Lots of talk on poltics as well with neighboring
corps. The corp is trying to train people to become officers and fleet
commanders for the corps so we can start doing organized content. It was
like I was sitting in on a war room brief lmao.

But I've made a ship to do wormhole exploration for data hacking and relic
recovery for mad ISK profits. You get blueprints to build ships or get
parts for expensive content. its risky af because you're in "null sec" and
can get shot down by anyone with no consequence!

Also I read through your writeup and I cant believe you were able to get
SSID and Password in PLAINTEXT!??!? WTF? The writeup is super cool, add
more pictures for normies like me next time :3

Also download EVE and I'll play w/ you late at night and we can try to go
on gank runs. One of us can be a "tackler" or "e-war" specialist to hold
down the enemy and get ez kills "hopefully" space is risky. But the game is
sooooo in depth its unbelievable with tactics and recon.
