### ISSUE TITLE
Add cross-compatibility to makefile

### ISSUE THREAD

**Issue by NealsSec** [Blizire/bbmp#6]
It looks like the makefile only works on Windows currently, I will try and patch it to work on Linux as well by looking for environmental variables to see if the system is Linux or windows.

**Comment by Blizire** [comment]
awesome I think for linux systems you might need to add the -fpic flag and just change the parameter for the -o flag to bbmp.so instead of bbmp.dll . Couldn't test myself becuase it was taking way to long to install gcc on my ubuntu term :[

**Comment by NealsSec** [comment]
I have created a pull request that should fix this issue. It definitely must be tested before merging.

**Comment by NealsSec** [comment]
Closing due to success in building from Windows.
